### ISSUE TITLE
Wrong unicode value for U+1F601,U+1F3FF

### ISSUE THREAD

**Issue by pedronavf** [emojidex/emojidex-rasters#1]
In emoji.json, the entry for "grinning_face_with_smiling_eyes(bk)" has the right moji value but the unicode field is missing an F. It says `"unicode":"1f6011f3f"` instead of `"unicode":"1f6011f3ff"`

**Comment by Kagetsuki** [comment]
Awesome catch @pedronavf ! Just fixed it in emojidex-vectors (rasters is compiled from vectors) and we'll be pushing full updates later this week. Thanks for the heads up.
